# Generated by Django 4.0.1 on 2022-01-20 23:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeOfAppeal',
            fields=[
                ('noticeOfAppealId', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('webCatsCaseNumber', models.CharField(max_length=50, null=True)),
                ('ceisFileId', models.IntegerField(blank=True, null=True)),
                ('accountId', models.IntegerField(null=True)),
                ('lowerCourtFileNo', models.CharField(max_length=20, null=True)),
                ('lowerCourtLevelCd', models.CharField(max_length=1, null=True)),
                ('lowerCourtLevelName', models.CharField(db_column='lowerCourtLevelName_Derived', max_length=50, null=True)),
                ('lowerCourtRegistryId', models.DecimalField(decimal_places=4, max_digits=20, null=True)),
                ('lowerCourtRegistryName', models.CharField(db_column='lowerCourtRegistryName_Derived', max_length=50, null=True)),
                ('lowerCourtClassCd', models.CharField(max_length=1, null=True)),
                ('lowerCourtClassName', models.CharField(db_column='lowerCourtClassName_Derived', max_length=50, null=True)),
                ('lowerCourtStyleOfCause', models.CharField(max_length=500, null=True)),
                ('nameOfJudge', models.CharField(max_length=100, null=True)),
                ('honorificTitle', models.CharField(max_length=50, null=True)),
                ('dateOfJudgement', models.DateTimeField(blank=True, null=True)),
                ('appealSubmissionDeadline', models.DateTimeField(blank=True, null=True)),
                ('trialDurationDays', models.IntegerField(blank=True, null=True)),
                ('respondentSolicitor', models.CharField(max_length=255, null=True)),
                ('appealingFirm', models.CharField(max_length=255, null=True)),
                ('appealingFirmAddress', models.CharField(max_length=255, null=True)),
                ('appealFrom', models.CharField(max_length=255, null=True)),
                ('wasSupremeAppeal', models.BooleanField(blank=True, default=False, null=True)),
                ('decisionMaker', models.CharField(max_length=100, null=True)),
                ('partOfJudgment', models.CharField(max_length=100, null=True)),
                ('refOptional', models.CharField(max_length=50, null=True)),
                ('orderSought', models.CharField(max_length=50, null=True)),
                ('protectionOrder', models.BooleanField(blank=True, default=False, null=True)),
                ('toRespondents', models.CharField(max_length=50, null=True)),
                ('lowerCourtInitiatingDocument', models.CharField(max_length=100, null=True)),
                ('involves', models.CharField(max_length=100, null=True)),
                ('readOnlyUsers', models.CharField(max_length=1000, null=True)),
                ('readWriteUsers', models.CharField(max_length=1000, null=True)),
                ('savedFromPage', models.CharField(max_length=10, null=True)),
                ('handTypedNoSearch', models.BooleanField(blank=True, default=False, null=True)),
                ('dateCreated', models.DateTimeField()),
                ('createdByClientId', models.IntegerField(null=True)),
                ('dateModified', models.DateTimeField()),
                ('lastModifiedByClientId', models.IntegerField(null=True)),
                ('dateSubmitted', models.DateTimeField(blank=True, null=True)),
                ('submittedByClientId', models.IntegerField(blank=True, null=True)),
                ('submittedByFullName', models.CharField(max_length=100, null=True)),
                ('electronicallyFiled', models.CharField(max_length=1, null=True)),
                ('dateProcessed', models.DateTimeField(blank=True, null=True)),
                ('webCatsResultCode', models.CharField(max_length=50, null=True)),
                ('selfRepresenting', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('partyId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('ceisPartyId', models.IntegerField(null=True)),
                ('isOrganization', models.BooleanField(blank=True, default=False, null=True)),
                ('prefix', models.CharField(max_length=100, null=True)),
                ('firstGivenName', models.CharField(max_length=100, null=True)),
                ('secondGivenName', models.CharField(max_length=100, null=True)),
                ('thirdGivenName', models.CharField(max_length=100, null=True)),
                ('surname', models.CharField(max_length=100, null=True)),
                ('organizationName', models.CharField(max_length=100, null=True)),
                ('counselName', models.CharField(max_length=255, null=True)),
                ('appealRole', models.CharField(max_length=50, null=True)),
                ('lowerCourtRole', models.CharField(max_length=255, null=True)),
                ('noticeOfAppeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='form7.noticeofappeal')),
            ],
        ),
        migrations.CreateModel(
            name='PartyLegalRep',
            fields=[
                ('partyLegalRepId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('repType', models.CharField(max_length=75, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legalReps', to='form7.party')),
            ],
        ),
        migrations.CreateModel(
            name='PartyAlias',
            fields=[
                ('partyAliasId', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('nameType', models.CharField(max_length=50, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='form7.party')),
            ],
        ),
        migrations.CreateModel(
            name='MSopParty',
            fields=[
                ('mSopPartyId', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('appealRole', models.CharField(max_length=50, null=True)),
                ('lowerCourtRole', models.CharField(max_length=255, null=True)),
                ('conjunction', models.CharField(max_length=255, null=True)),
                ('partyName', models.CharField(max_length=4000, null=True)),
                ('plural', models.BooleanField(blank=True, default=False, null=True)),
                ('noticeOfAppeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manualSop', to='form7.noticeofappeal')),
            ],
        ),
    ]
