# Generated by Django 4.0.1 on 2022-01-27 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form7', '0002_formpdf_formpdf_unique_pdf_type_noticeofappeal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeofappeal',
            name='package_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='noticeofappeal',
            name='package_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='noticeofappeal',
            name='submission_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='noticeofappeal',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formpdf',
            name='noticeOfAppeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form7.noticeofappeal'),
        ),
    ]
