# Generated by Django 4.0.1 on 2022-01-29 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form7', '0002_formpdf_formpdf_unique_pdf_type_noticeofappeal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpdf',
            name='noticeOfAppeal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeal_form_pdf', to='form7.noticeofappeal'),
        ),
    ]
