# Generated by Django 4.0.1 on 2022-04-22 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form7', '0003_noticeofappeal_package_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeOfUrgentApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField()),
                ('modified', models.DateTimeField()),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('last_filed', models.DateTimeField(blank=True, null=True)),
                ('submission_id', models.CharField(max_length=100, null=True)),
                ('transaction_id', models.CharField(max_length=100, null=True)),
                ('package_number', models.CharField(max_length=100, null=True)),
                ('package_url', models.CharField(max_length=200, null=True)),
                ('pdf_types', models.CharField(blank=True, default='', max_length=100)),
                ('last_printed', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('key_id', models.CharField(blank=True, max_length=32, null=True)),
                ('data', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='msopparty',
            name='noticeOfAppeal',
        ),
        migrations.RemoveField(
            model_name='party',
            name='noticeOfAppeal',
        ),
        migrations.RemoveField(
            model_name='partyalias',
            name='party',
        ),
        migrations.RemoveField(
            model_name='partylegalrep',
            name='party',
        ),
        migrations.RemoveConstraint(
            model_name='formpdf',
            name='unique_pdf_type_noticeOfAppeal_id',
        ),
        migrations.RemoveField(
            model_name='formpdf',
            name='noticeOfAppeal',
        ),        
        migrations.DeleteModel(
            name='MSopParty',
        ),
        migrations.DeleteModel(
            name='NoticeOfAppeal',
        ),
        migrations.DeleteModel(
            name='Party',
        ),
        migrations.DeleteModel(
            name='PartyAlias',
        ),
        migrations.DeleteModel(
            name='PartyLegalRep',
        ),
        migrations.AddField(
            model_name='noticeofurgentapplication',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notice_of_urgent_application_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formpdf',
            name='notice_of_urgent_application',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notice_of_urgent_application_form_pdf', to='form7.noticeofurgentapplication'),
        ),
        migrations.AddConstraint(
            model_name='formpdf',
            constraint=models.UniqueConstraint(fields=('notice_of_urgent_application_id', 'pdf_type'), name='unique_pdf_type_notice_of_urgent_application_id'),
        ),
    ]
