# Generated by Django 3.2.8 on 2021-10-30 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(blank=True, default='', max_length=100)),
                ('modified', models.DateTimeField(blank=True, null=True)),
                ('package_url', models.CharField(max_length=200, null=True)),
                ('key_id', models.CharField(blank=True, max_length=32, null=True)),
                ('data', models.BinaryField(blank=True, null=True)),
                ('package_number', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_user_Id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PreparedPdf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('data', models.BinaryField(blank=True, null=True)),
                ('json_data', models.BinaryField(blank=True, null=True)),
                ('key_id', models.CharField(blank=True, max_length=32, null=True)),
                ('pdf_type', models.CharField(blank=True, max_length=32, null=True)),
                ('version', models.CharField(blank=True, max_length=32, null=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_pdf_case_id', to='api.case')),
            ],
        ),
        migrations.CreateModel(
            name='Journeymap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(blank=True, max_length=32, null=True)),
                ('steps', models.BinaryField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_user_Id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='preparedpdf',
            constraint=models.UniqueConstraint(fields=('case_id', 'pdf_type'), name='unique_pdf_type_case_id'),
        ),
    ]
