# Generated by Django 3.2.8 on 2021-11-03 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211030_0137'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='archive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='pdf_types',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
