# Generated by Django 3.2.8 on 2021-11-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_case_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='last_filed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='last_printed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='submission_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='transaction_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='EFilingSubmission',
        ),
    ]
