# Generated by Django 4.0.1 on 2022-03-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_user_account_id_user_client_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='represented',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
