# Generated by Django 4.0.1 on 2022-07-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_user_represented'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='archive',
        ),
        migrations.AddField(
            model_name='case',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
