---
kind: Template
apiVersion: v1
metadata:
  name: ${NAME}
objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${NAME}
  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
    spec:
      triggers:
        - type: ConfigChange
      runPolicy: Serial
      source:
        type: Git
        git:
          ref: ${GIT_REF}
          uri: ${GIT_REPO_URL}
        contextDir: ${SOURCE_CONTEXT_DIR}
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: ${DOCKER_FILE_PATH}
          from:
            kind: "${SOURCE_IMAGE_KIND}"
            name: "${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}"
      output:
        to:
          kind: ImageStreamTag
          name: ${NAME}:${OUTPUT_IMAGE_TAG}
parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the frontend objects defined in this template.  You should keep this as default unless your know what your doing.
    required: true
    value: web-builder
  - name: GIT_REPO_URL
    displayName: Git Repo URL
    description: The URL to your GIT repo.
    required: true
    value: https://github.com/bcgov/court-of-appeal.git
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
    value: main
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: true
    value: docker/yarn-builder/

  - name: SOURCE_IMAGE_KIND
    displayName: Source Image Kind
    description: The 'kind' (type) of the  source image; typically ImageStreamTag, or DockerImage.
    required: true
    value: DockerImage
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the source image.
    required: true
    value: docker-remote.artifacts.developer.gov.bc.ca/centos/nodejs-12-centos7
  - name: SOURCE_IMAGE_TAG
    displayName: Source Image Tag
    description: The tag of the source image.
    required: true
    value: latest

  - name: DOCKER_FILE_PATH
    displayName: Docker File Path
    description: The path to the docker file defining the build.
    required: false
    value: Dockerfile
  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
    value: latest
